var n1,n2,soma,sub,mult,div
n1=prompt("Digite o primeiro valor: ")
n2=prompt("Digite o segundo valor: ")
soma=parseFloat(n1)+parseFloat(n2)
alert("A soma é: " +soma)
sub=parseFloat(n1)-parseFloat(n2)
alert("A subtração é: " +sub)
mult=parseFloat(n1)*parseFloat(n2)
alert("A multiplicação é: " +mult)
div=parseFloat(n1)/parseFloat(n2)
alert("A divisão é: " +div)